// priority: 0

onEvent('block.registry', event => {
  event.create('block_conductive_iron')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Conductive Iron Block')

  event.create('block_construction_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Construction Alloy Block')

  event.create('block_crude_steel')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Crude Steel Block')

  event.create('block_crystalline_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Crystalline Alloy Block')

  event.create('block_crystalline_pink_slime')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Crystalline Pink Slime Block')

  event.create('block_dark_steel')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Dark Steel Block')

  event.create('block_electrical_steel')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Eletrical Steel Block')

  event.create('block_end_steel')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('End Steel Block')

  event.create('block_energetic_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Energetic Alloy Block')

  event.create('block_energetic_silver')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Energetic Silver Block')

  event.create('block_gelid_crystal')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Gelid Crystal Block')

  event.create('block_gelid_enderium')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Gelid Enderium Block')

  event.create('block_industrial_insulation')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Industrial Insulation Block')

  event.create('block_infinity_0')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Infinity 0 Block')

  event.create('block_infinity_1')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Infinity 1 Block')

  event.create('block_infinity_2')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Infinity 2 Block')

  event.create('block_melodic_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Melodic Alloy Block')

  event.create('block_pulsating_iron')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Pulsating Iron Block')

  event.create('block_redstone_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Redstone Alloy Block')

  event.create('block_soularium')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Soularium Block')

  event.create('block_stellar_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Stellar Alloy Block')

  event.create('block_vibrant_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Vibrant Alloy Block')

  event.create('block_vivid_alloy')
    .material('stone')
    .hardness(5.0)
    .tagBlock('minecraft:requries_iron_tool')
    .fullBlock(true)
    .displayName('Vivid Alloy Block')
})
