
onEvent('recipes', e => {

  function maker(molten, output){
        e.recipes.custommachinery.custom_machine("custommachinery:plate_maker", 80)
            .requireFluid(Fluid.of(molten, 100))
            .requireEnergy(2000)
            .produceItem(output, "output1")
    }

    maker('kubejs:molten_desh', '#forge:plates/desh')
    maker('kubejs:molten_iron', '#forge:plates/iron')
    maker('kubejs:molten_steel', '#forge:plates/steel')
    maker('kubejs:molten_rose_gold', '#forge:plates/rose_gold')
    maker('kubejs:molten_gold', '#forge:plates/gold')
    maker('kubejs:molten_copper', '#forge:plates/copper')
    maker('kubejs:molten_netherite', '#forge:plates/netherite')
    maker('kubejs:molten_tin', '#forge:plates/tin')
    maker('kubejs:molten_lead', '#forge:plates/lead')
    maker('kubejs:molten_silver', '#forge:plates/silver')
    maker('kubejs:molten_nickel', '#forge:plates/nickel')
    maker('kubejs:molten_bronze', '#forge:plates/bronze')
    maker('kubejs:molten_electrum', '#forge:plates/electrum')
    maker('kubejs:molten_invar', '#forge:plates/invar')
    maker('kubejs:molten_constantan', '#forge:plates/constantan')
    maker('kubejs:molten_signalum', '#forge:plates/signalum')
    maker('kubejs:molten_lumium', '#forge:plates/lumium')
    maker('kubejs:molten_enderium', '#forge:plates/enderium')
    maker('thermal_extra:dragon_bronze', '#forge:plates/dragon_bronze')
    maker('thermal_extra:dragon_enderium', '#forge:plates/dragon_enderium')
    maker('thermal_extra:vukaium', '#forge:plates/vukaium')
    maker('thermal_extra:nebulium', '#forge:plates/nebulium')
    maker('thermal_extra:nectium', '#forge:plates/nectium')
    maker('thermal_extra:polarium', '#forge:plates/polarium')
    maker('thermal_extra:zauvium', '#forge:plates/zauvium')
    maker('thermal_extra:drownium', '#forge:plates/drownium')
    maker('kubejs:molten_aluminum', '#forge:plates/aluminum')
    maker('kubejs:molten_iridium', '#forge:plates/iridium')
    maker('kubejs:molten_osmium', '#forge:plates/osmium')
    maker('kubejs:molten_platinum', '#forge:plates/platinum')
    maker('kubejs:molten_uranium', '#forge:plates/uranium')
    maker('kubejs:molten_zinc', '#forge:plates/zinc')
    maker('kubejs:molten_brass', '#forge:plates/brass')
  })
