
onEvent('recipes', e => {

  e.recipes.custommachinery.custom_machine("custommachinery:slice_n_splice", 80)
      .requireFluid(Fluid.of("kubejs:liquid_nutrient_distillation", 2000))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('minecraft:rotten_flesh'))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('ae2:silicon'))
      .requireItem(Item.of('thermal:rf_coil'))
      .requireItem(Item.of('rftoolsutility:syringe', '{level:10,mobId:"minecraft:zombie",mobName:"minecraft:zombie"}'))
      .requireEnergy(20000)
      .produceItem('kubejs:zombie_electrode', "output1")

    e.recipes.custommachinery.custom_machine("custommachinery:slice_n_splice", 80)
      .requireFluid(Fluid.of("kubejs:liquid_nutrient_distillation", 2000))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('minecraft:rotten_flesh'))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('ae2:silicon'))
      .requireItem(Item.of('thermal:rf_coil'))
      .requireItem(Item.of('hostilenetworks:prediction', '{data_model:{id:"hostilenetworks:zombie"}}'))
      .requireEnergy(10000)
      .produceItem('kubejs:zombie_electrode', "output1")

  e.recipes.custommachinery.custom_machine("custommachinery:slice_n_splice", 80)
      .requireFluid(Fluid.of("kubejs:liquid_nutrient_distillation", 2000))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('minecraft:rotten_flesh'))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('ae2:silicon'))
      .requireItem(Item.of('thermal:rf_coil'))
      .requireItem(Item.of('rftoolsutility:syringe', '{level:10,mobId:"minecraft:enderman",mobName:"minecraft:enderman"}'))
      .requireEnergy(20000)
      .produceItem('kubejs:ender_resonator', "output1")

    e.recipes.custommachinery.custom_machine("custommachinery:slice_n_splice", 80)
      .requireFluid(Fluid.of("kubejs:liquid_nutrient_distillation", 2000))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('minecraft:rotten_flesh'))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('ae2:silicon'))
      .requireItem(Item.of('thermal:rf_coil'))
      .requireItem(Item.of('hostilenetworks:prediction', '{data_model:{id:"hostilenetworks:enderman"}}'))
      .requireEnergy(10000)
      .produceItem('kubejs:ender_resonator', "output1")

    e.recipes.custommachinery.custom_machine("custommachinery:slice_n_splice", 80)
      .requireFluid(Fluid.of("kubejs:liquid_nutrient_distillation", 2000))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('minecraft:rotten_flesh'))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('ae2:silicon'))
      .requireItem(Item.of('thermal:rf_coil'))
      .requireItem(Item.of('rftoolsutility:syringe', '{level:10,mobId:"minecraft:skeleton",mobName:"minecraft:skeleton"}'))
      .requireEnergy(20000)
      .produceItem('kubejs:skeleton_electrode', "output1")

    e.recipes.custommachinery.custom_machine("custommachinery:slice_n_splice", 80)
      .requireFluid(Fluid.of("kubejs:liquid_nutrient_distillation", 2000))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('minecraft:rotten_flesh'))
      .requireItem(Item.of('kubejs:ingot_soularium'))
      .requireItem(Item.of('ae2:silicon'))
      .requireItem(Item.of('thermal:rf_coil'))
      .requireItem(Item.of('hostilenetworks:prediction', '{data_model:{id:"hostilenetworks:skeleton"}}'))
      .requireEnergy(10000)
      .produceItem('kubejs:skeleton_electrode', "output1")

})
